spring:
  activemq:
    broker-url: "vm://delete"
    user: admin
    password: password
  datasource:
    url: jdbc:mariadb://localhost:3306/junkschema
    username: root
    password: master
  jms:
    template:
      default-destination: delete
  jta:
    atomikos:
      properties:
        log-base-dir: delete-transaction-log
        transaction-manager-unique-name: delete-tm
